color: null
fieldLayouts:
  f08482e0-749a-4a71-9093-01b12cfa705a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 617aef04-a403-4526-98aa-139825209fcf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c11e3598-e2a3-446a-a21d-385c85387ec5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56b2328e-86c1-4a27-8d46-aaf0cbf8e4d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc1055c1-a55c-4b52-9e4e-af0c208776cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d48881f7-b42a-4fc9-9085-1472840ab182
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00ccf12a-849f-41aa-80f7-12eb8b9fb230
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aeac151d-d4a9-4733-9c2f-c8a1eac9a41b # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89b7bcc1-563b-47d8-941d-b805a07d51f3
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: c54b7104-c058-41f4-ac16-278920cf8062 # Container Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dff58c11-d667-4e04-bb82-5e3d42415531
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6065b222-611d-42ce-a1de-85a02891694c # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d0856c9-bf65-4c60-b749-0e2507ebded9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f36b49ea-9938-42fb-9803-9772a378f173 # Overlay Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 241e0a90-34d3-4fae-aa77-64037d66341d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cfc164dd-7161-4a3d-9407-1080228e7455 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a859a900-bf95-4e74-8848-c074c11ec0b0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e05fb8e0-726b-4a55-b97f-aea98a58c8a1 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7703a76-5dac-41bb-b0fe-8ab6696f51d2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ef7dff82-7ddc-453d-b03e-6b90683f02bd # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e29a0d6c-60f6-4459-a32b-c9dac8169cd3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9b22f7dd-9a2a-4565-8f39-2dcfdaf10712
            userCondition: null
          -
            elementCondition: null
            fieldUid: d07b837d-c20e-48d9-ac52-34b7a29fbfcb # Container Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7da4547f-d65f-477f-bdac-d024aac43754
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 276120e4-33d6-42f7-b15e-74f6f38e41bb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d3ab5ad8-585b-43bc-b8ad-c093a04c787f # Minus Margin Top (Deprecated)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c796d6dc-73d8-40ad-8a51-d1cd64a4d465
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 721f6c59-d353-4810-9d84-eee327f296be # Minus Margin Bottom (Deprecated)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11f5d0ab-1ea6-4000-9ea0-520af6ba5141
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 92bfd75d-d41c-4f68-9212-eba6699c22ba
            userCondition: null
          -
            elementCondition: null
            fieldUid: bcbc592a-d4d0-4afa-92b6-458504f09b17 # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c594f9a-b1a5-4c62-abf6-8881d8fde1b9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9affc432-fe49-4e90-96ea-be5425095c2c # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 546ccfbb-4412-449a-af5c-38fe69c5458d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3c44034a-42a6-4e12-a863-4f3cc325f1a4 # Padding Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72131abd-fa1d-4ddd-963c-18adc978836b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 18de2689-3603-4c37-8473-396f9ce4f78c # Padding Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 054c6644-c958-439b-8068-38a8feb03221
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 26879a45-4ef6-4b01-87ce-a984385797c7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 21102308-0ca8-4b67-8663-daef265f4c60 # Animation?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f308e750-9024-464b-b4ee-4bd9c4f7686b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5a7bd283-4c7d-4683-9176-d9ac24828bc0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3b2d250a-efd7-4394-9e59-a1ae3b9d5292 # Animation Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 009f9233-7929-4940-8ec1-8b706db53c91
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8df78e11-4ebe-4815-a6a8-a9a62e77b6d6 # Animation Easing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 036a9087-5a41-44a3-ba81-86e1a7239950
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e0e47b5e-62b4-4b02-aeca-99868e8625d9 # Animation Duration
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3113274-852f-4fc5-9bd8-7f4f8f6b0a65
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e13a17a-1829-4ccb-a64f-c39b6d62af82 # Animation Offset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89d10b85-80a9-4ade-b0d6-8e5b24c3707b
            userCondition: null
            warning: null
            width: 50
        name: Animation
        uid: a1f3aca0-cc2f-46bf-b911-1527083b7d6f
        userCondition: null
handle: basicContent
hasTitleField: false
icon: bars
name: 'Basic Content'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
