color: null
fieldLayouts:
  c8f075fc-d777-4754-986d-37b10f6c7c19:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a8cf1f26-86bc-4ee0-89a3-6f0513376e15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3398061-2f21-4e33-9dec-04cb79d4a8e9 # Check List
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf647c68-cc58-4f29-b036-56bcd714c51e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d34dc916-1170-4612-9d74-2eef715968ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87d73352-c942-44e5-8013-ca6f22bef372
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb909fb5-0be0-4965-b1f9-bbb31fe780f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 281112ac-cb8a-4a76-8656-786cd3761348
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2c7277d-8ebb-4e62-b76c-88f8ed968fab
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: 687c4b1f-5351-4b9c-9564-5b7650df2719
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Block Setting'
            type: craft\fieldlayoutelements\Heading
            uid: 7936ea7d-ccdc-4b73-8f67-206783be64b0
            userCondition: null
          -
            elementCondition: null
            fieldUid: aeac151d-d4a9-4733-9c2f-c8a1eac9a41b # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d80c967d-6a46-4b1e-a061-95f84cc75fe3
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: c54b7104-c058-41f4-ac16-278920cf8062 # Container Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05361a93-c1ac-415c-b8e2-48910a39e386
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6065b222-611d-42ce-a1de-85a02891694c # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e9bef64-093c-4b0f-adb9-e8bf3018cf7d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f36b49ea-9938-42fb-9803-9772a378f173 # Overlay Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22c6738f-27fd-49a2-909e-ab13161f9282
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ab7328c2-0ac9-4a96-8ed5-054ee9e45cbf # Per Row Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b987a36-8351-40b2-bada-41ce41c18878
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 0c894dc9-e8b7-472f-af76-8e1d482a9b61
            userCondition: null
          -
            elementCondition: null
            fieldUid: cfc164dd-7161-4a3d-9407-1080228e7455 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52f97f35-64b3-4633-8a08-54b7dd621ba7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e05fb8e0-726b-4a55-b97f-aea98a58c8a1 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2da32160-720d-48b3-89d6-6be306298389
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ef7dff82-7ddc-453d-b03e-6b90683f02bd # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce7e1807-59d6-467c-80d5-7a724a26df02
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5fb2452e-42f1-4903-b373-197fd2bd45f3
            userCondition: null
          -
            elementCondition: null
            fieldUid: d07b837d-c20e-48d9-ac52-34b7a29fbfcb # Container Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5189b3c-0d3f-4b66-b0d1-d10c53eec532
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 69bea4e4-36a1-4a91-af4d-76df6a572b95
        userCondition: null
handle: checklist
hasTitleField: false
icon: check
name: Checklist
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
