color: null
fieldLayouts:
  d66cbc0d-ed4e-479e-8795-cc0ddc11be65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97a34988-60e7-4f45-97ec-a90e83ef3984
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b15cab4-22ae-40f3-9612-204b951f30f0
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fa7bfc3-c8b2-4c79-b5ea-2ed08be94b71
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7f018fb5-73a1-482a-97e6-20b925125348
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cac9d8ae-fa4a-41f1-bd28-706f8fe4a6d2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b03ebf6d-328a-417c-a206-f3015411d968
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47a05dfe-2116-4967-b660-82ef58f8c8e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed3f5117-0a7a-49dc-b888-5b62a1e32b81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90a810f2-de87-4697-8abf-8e6e2c825c72
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02d36092-09e2-4d66-ad7f-1242ca54c05f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56196e9b-e1c4-44b3-817a-0f471121ed32
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25977bf3-2f5d-4c99-8e06-84ef8b136565
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0afe19b2-8522-4397-b3be-fc4e5662becb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da48f115-2f42-4554-ac1d-f39d6640c257
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f91899a-7513-48fd-a8fc-92a7382172a8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 021cf0d0-1863-4788-aeb4-6225da5b03a9
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f21ae3d-6f55-4c8e-97d1-1f5a83c4d114
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: c2a01ec3-4c2e-4aa1-b82c-9c5bb1052604
        userCondition: null
handle: ImageContentSlide
hasTitleField: false
icon: images
name: 'Image Content Slide'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
