color: null
fieldLayouts:
  e1734063-e64c-4811-ba71-5b490de0ceea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 410170e3-98ed-45da-951a-0dbe5594280c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 948968bb-c8d8-4627-aaa9-aa1b20ada200 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73a00abe-48b9-407b-8a1e-f49b597d20c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c14150f6-d51e-480d-9575-1091c8b07cb1 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28fb787a-940e-4bc0-ab66-031f40770cf8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 14f10c33-05fc-403a-8956-c0dcd6fcae9d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 45decbb3-802d-4a8a-9b63-3067d0c45d17 # Require Login?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a85252ec-5df5-4a4c-897e-6efccbe9a8de
            userCondition: null
            warning: null
            width: 100
        name: Login
        uid: b5203d00-38e6-4b36-b0e9-c4ad44b7bff5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 423bb166-71e5-4c7c-9d8c-71db99966b0b # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: SEO
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80df2c1e-0e8e-47ff-b991-7dde565b73f6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 18dfddb6-6cfb-4756-b60f-97974df18f57
        userCondition: null
handle: pageBuilder
hasTitleField: true
icon: shapes
name: 'Page Builder'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
