color: null
fieldLayouts:
  bdb16cab-8f96-445d-bb44-102049d6d0d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 990e0d4b-6f97-4bfc-9df6-5152565ef0df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b15cab4-22ae-40f3-9612-204b951f30f0 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee77ee17-10fa-45b9-8dab-9766245a44a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 911e36c6-e57b-4265-b8ca-b5b75d400e90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f32477a-6b0a-4125-a481-7ddbf9b1cec5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdfad3c8-2ba3-459f-adfe-f02e70bcc4a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f8896529-04ad-45ec-a9d8-e38b1dd1156d
        userCondition: null
handle: split
hasTitleField: false
icon: ''
name: Split
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
