color: null
fieldLayouts:
  2e20d12d-d287-43ec-a3ae-ace693310800:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7eef673a-b007-4d75-8271-70089b2f3d9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ae7d75d-cf9a-41db-b14d-a11c5a609f43 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bc1c646-5475-4861-927f-20eb1e223d75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5a942ed-23a8-4ef6-a414-f5b0fdfaadcb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64fbaa56-bb99-4f28-bfcb-1ca397ded21b
        userCondition: null
handle: stackedCard
hasTitleField: false
icon: layer-group
name: 'Stacked Card'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
