color: indigo
fieldLayouts:
  72b18d3f-1157-430a-b6c3-20e427602214:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d0fa0aaa-d583-4913-90c7-43aca09c8460
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b89198b-d038-4943-ae58-1f0c6d1ccc8d # Stage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61a7b9cf-f896-44f2-8814-066c0261302b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 571eaa99-3b98-41a7-8942-c300b3c2fe5b # Byline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 073e8986-f87b-4a5d-b9fd-6f222b7ba79c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: protectionTargetHeading
            includeInCards: false
            instructions: null
            label: 'Protection Target Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d85e029-50b8-47b8-bd5d-5198e928aff7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 198cf762-0cd8-47c3-94c5-d342b3225447
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dcc4c3a7-d1ad-429a-8db7-6eb780b2d453 # Dots in group of
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7b95290-ba31-4031-9337-6f73c5bd10c7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7bc32678-0f69-4111-926c-26e502c0c7fc # 1 Blank at?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 355d5262-e0eb-48eb-ab82-89111fd70dda
            userCondition: null
            warning: null
            width: 50
        name: Dots
        uid: 44b665fe-91aa-4ef2-918e-a9d8a0466526
        userCondition: null
handle: stagesMatrix
hasTitleField: false
icon: wagon-covered
name: Stages
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
