color: null
fieldLayouts:
  ebd54f89-78a3-41ca-b4e6-87c5baf09a23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e987ba8-08ff-4354-8731-836da93e469d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41ced047-3000-48fa-8166-c609bb010579
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 386b0909-e113-485b-9c5c-f3c4a42a8edd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 448af70e-ada1-4c86-90cc-2d596ce73685
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0aa1b297-6e97-4b8a-9fc1-85426a8112b3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b1490ff-33de-47f1-9180-954b3a22aebd
        userCondition: null
handle: statBox
hasTitleField: false
icon: signal
name: 'Stat Box'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
