color: null
fieldLayouts:
  8e92a24c-eae8-4f8f-8242-375a7b652a20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4055f6ee-789b-4b1a-9aad-b89e7f68083f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6d4db04-3637-41c9-a16d-e729d6eb58ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba158caf-409c-4787-b23e-c0b508ed6dac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05f4aa96-2a20-4f5a-af29-371b169a6725 # Current Status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74b92311-ae0a-4495-9a03-6d7435264d08
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 8257b009-c3c8-4465-beb9-fa52c9b6be4f # Status Color 
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d326f9f3-2dba-4b47-a8a2-f31757c330dc
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d9d84af-b06f-4fa3-ba0c-ae44a5f7a9a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d73bc95a-b379-4611-8b6e-a34fb2b6d840
        userCondition: null
handle: statusCard
hasTitleField: false
icon: signal
name: 'Status Card'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
