headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Advanced
options:
  alignment:
    options:
      - left
      - center
      - right
  style:
    definitions:
      -
        classes:
          - red-heading
        element: h2
        name: 'Red heading'
      -
        classes:
          - vibrant-code
        element: pre
        name: 'Vibrant code'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - code
  - sourceEditing
  - heading
  - style
  - '|'
  - alignment
  - '|'
  - underline
  - subscript
  - strikethrough
  - bold
  - italic
  - insertImage
  - mediaEmbed
  - fontColor
  - blockQuote
  - insertTable
  - '|'
  - bulletedList
  - numberedList
  - todoList
  - horizontalLine
  - pageBreak
  - '|'
  - link
