altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  7c2e08b2-d2d6-420b-bce0-dc08e2385c27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ae672349-306f-4bfd-9085-829ebc52395d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d6601af9-a397-434f-99bf-9364f8a33085
        userCondition: null
fs: videos
handle: videos
name: Videos
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: ''
