columnSuffix: null
handle: address
instructions: null
name: Address
searchable: false
settings:
  boundary: '""'
  boundaryRestrictionNELat: null
  boundaryRestrictionNELng: null
  boundaryRestrictionSWLat: null
  boundaryRestrictionSWLng: null
  country: null
  countryRestriction: null
  height: null
  hideAddress: false
  hideLatLng: null
  hideMap: false
  hideSearch: false
  lat: 51.272154
  lng: 0.514951
  maxZoom: 18.0
  minZoom: 3.0
  showCurrentLocation: false
  showLatLng: true
  showW3WField: false
  showW3WGrid: false
  size: normal
  typeRestriction: null
  zoom: 15
translationKeyFormat: null
translationMethod: none
type: ether\simplemap\fields\MapField
