columnSuffix: null
handle: animationStyle
instructions: null
name: 'Animation Style'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: null
  json: ''
  template: _/sdf/animationStyle.json
  templateData: null
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
