columnSuffix: null
handle: buttons
instructions: null
name: Buttons
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 383b8156-a3da-4bda-991a-7c9893a1c11c # Button
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
