columnSuffix: null
handle: byline
instructions: null
name: Byline
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 970e66f8-69d9-430c-b4f9-74359ab8d3bd # Advanced
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
