columnSuffix: null
handle: card
instructions: null
name: Card
searchable: false
settings:
  createButtonLabel: Card
  entryTypes:
    - 23661aee-cd9b-46df-9aa0-3f931f87ba19 # card
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
