columnSuffix: null
handle: checkList
instructions: null
name: 'Check List'
searchable: false
settings:
  createButtonLabel: 'Check List'
  entryTypes:
    - aa174fd2-f4fc-4970-af80-40e62b2d07cb # Check List
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
