columnSuffix: null
handle: columnLayout
instructions: null
name: 'Column Layout'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: null
  json: ''
  template: _/sdf/columnLayout.json
  templateData: null
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
