columnSuffix: null
handle: containerId
instructions: "ID attribute of this block. Leave this empty will generate dynamic ID.\r\nID will be auto converted into kebab-case"
name: 'Container Id'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
