columnSuffix: null
handle: imageContents
instructions: null
name: 'Image Contents'
searchable: false
settings:
  createButtonLabel: 'Image Content'
  entryTypes:
    - 9ea500de-6e50-41cc-a7ad-a1a5aeb0aca6 # Slide
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
