columnSuffix: null
handle: minusMarginBottom
instructions: null
name: 'Minus Margin Bottom (Deprecated)'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: ''
  json: ''
  template: _/sdf/spacing.json
  templateData: ''
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
