columnSuffix: null
handle: minusMarginTop
instructions: null
name: 'Minus Margin Top (Deprecated)'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: null
  json: ''
  template: _/sdf/spacing.json
  templateData: null
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
