columnSuffix: null
handle: overlayGradient
instructions: null
name: 'Overlay Gradient'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: null
  json: ''
  template: _/sdf/ovarlayGradient.json
  templateData: null
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicCheckboxesField
