columnSuffix: null
handle: scriptFiles
instructions: null
name: 'Script Files'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - URL
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Type
            -
              - handle
              - type
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - JS
                    -
                      - value
                      - js
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - CSS
                    -
                      - value
                      - css
                    -
                      - default
                      - false
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Attributes
            -
              - handle
              - attributes
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - js
        -
          - col3
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
