columnSuffix: null
handle: stages
instructions: null
name: Stages
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - f8f1ebd9-1ace-4716-a3fc-03f5bcf95cbd # Stages
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
