columnSuffix: null
handle: statusCard
instructions: null
name: 'Status Card'
searchable: false
settings:
  createButtonLabel: Card
  entryTypes:
    - 493bf7e3-b061-45e5-92e4-2f401b9a8e5a
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
