columnSuffix: null
handle: statBox
instructions: null
name: 'Stat Box'
searchable: false
settings:
  createButtonLabel: 'Stat Box'
  entryTypes:
    - 10939aae-e10b-4be1-8d12-358d50ce590d # Stat Box
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
