columnSuffix: null
handle: trackingScripts
instructions: null
name: 'Tracking Scripts'
searchable: false
settings:
  createButtonLabel: 'Tracking Script'
  entryTypes:
    - 67356d1e-de3d-4ceb-85ad-abf6b08ff9d2 # Tracking Script
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
