dateModified: 1719901315
email:
  fromEmail: mufi@paragonn.com
  fromName: 'IJM Program Tracker'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -t -i'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/uploads/transforms'
    type: craft\fs\Local
    url: '@web/uploads/transforms'
  videos:
    hasUrls: true
    name: Videos
    settings:
      path: '@webroot/uploads/videos'
    type: craft\fs\Local
    url: '@web/uploads/videos'
meta:
  __names__:
    0b15cab4-22ae-40f3-9612-204b951f30f0: Image # Image
    0bb1f59a-bac9-4368-b972-bc346cf78bdb: Links # Links
    0e13a17a-1829-4ccb-a64f-c39b6d62af82: 'Animation Offset' # Animation Offset
    0e63aa9f-6064-4094-ab28-0b9e7f6b8f09: 'Image + Content' # Image + Content
    00f64a37-6342-4ab0-a52b-d24123cb37e0: 'Info Box' # Info Box
    1da620f4-95cb-4911-9332-8ef04cad860f: Button # Button
    2e9cec4b-7c08-4594-a616-22bb4a04cba8: Brands # Brands
    3b2d250a-efd7-4394-9e59-a1ae3b9d5292: 'Animation Style' # Animation Style
    3bf73e53-2279-498c-9693-f24c6e498172: 'Page Builder' # Page Builder
    3c44034a-42a6-4e12-a863-4f3cc325f1a4: 'Padding Top' # Padding Top
    3d6985d0-6c25-467d-8334-100bb6a30cce: 'Call to Action' # Call to Action
    3fc2d296-ed56-4d93-a0e3-435f9f12a54c: CTA # CTA
    4b89198b-d038-4943-ae58-1f0c6d1ccc8d: Stage # Stage
    4f72c1ee-9438-4229-aa23-ef809d4af047: Logo # Logo
    5a2e4125-53c6-4343-b44e-970c058d6ba3: 'Projects Search Feature with MapBox' # Projects Search Feature with MapBox
    5c6bb440-978c-4cab-8939-e7991f378b17: Custom # Custom
    5c654d1e-8c51-46d6-9baa-d89900c8051a: 'Icon Card' # Icon Card
    5d2385da-c451-4d15-a8dc-9bf204cfb717: Eyebrow # Eyebrow
    5e460cf8-38e4-4ac9-8629-0c53ed9052c4: Jurisdictions # Jurisdictions
    6ae7d75d-cf9a-41db-b14d-a11c5a609f43: Icon # Icon
    7bc32678-0f69-4111-926c-26e502c0c7fc: '1 Blank at?' # 1 Blank at?
    7be90189-1791-495b-a850-3bc340df0caf: Casework # Casework
    7d09c5e7-e849-465a-9e4f-087bdef82bb4: Caption # Caption
    7f018fb5-73a1-482a-97e6-20b925125348: Videos # Videos
    7fe9589b-0f2b-4c94-91b8-f1e030710e58: Regular # Regular
    8df78e11-4ebe-4815-a6a8-a9a62e77b6d6: 'Animation Easing' # Animation Easing
    8ee03cb6-c673-4aca-b24c-41391b451ecf: 'Number of Dots' # Number of Dots
    08f0c8e2-e9c0-426a-aab3-861fbf413a1f: Heading # Heading
    8fe9110f-04ca-4e39-bd2e-0bce67301c39: Simple # Simple
    9affc432-fe49-4e90-96ea-be5425095c2c: 'Margin Bottom' # Margin Bottom
    9ce08183-1391-4b24-8288-a39ac4f97186: 'Image Ratio' # Image Ratio
    9ea500de-6e50-41cc-a7ad-a1a5aeb0aca6: 'Image Content Slide' # Image Content Slide
    9eeafc05-3901-41da-8748-e04485b292cb: 'Button Type' # Button Type
    14cf885b-68f2-4ea2-8f07-4a707cc2677f: 'Info Box Layout' # Info Box Layout
    16c21eca-a8b2-4b44-bd82-463fac26b779: 'Icon Cards' # Icon Cards
    18de2689-3603-4c37-8473-396f9ce4f78c: 'Padding Bottom' # Padding Bottom
    021cf0d0-1863-4788-aeb4-6225da5b03a9: 'Embed Video' # Embed Video
    26c9ce02-0df9-486a-90b7-104efcd7f5a8: 'Content Box Color' # Content Box Color
    28f860da-7e14-4288-a55f-bce3b2856d85: Text # Text
    60cbc150-308a-4195-882f-fe574c5af2d0: Image # Image
    061c5a97-e8a9-4593-9f93-8a54597d62b4: 'IJM Program Tracker' # IJM Program Tracker
    71fa55a9-c465-4fe2-91f2-ee5a739774a9: 'Overlay Gradient' # Overlay Gradient
    75f7ed78-7f7c-432f-a6f5-b028a8b82c52: Stages # Stages
    89cc861f-51a9-49de-9637-831af3da0e7a: 'Border Color' # Border Color
    089d8bf1-7cfe-4f80-bf8b-517fa9e233e0: 'Call to Action' # Call to Action
    95b9f0e3-06b5-4fdf-add4-4d87ad204c7e: Address # Address
    383b8156-a3da-4bda-991a-7c9893a1c11c: Button # Button
    423bb166-71e5-4c7c-9d8c-71db99966b0b: SEO # SEO
    451e39c8-4f34-47b0-9a76-9fae1d662c17: Columns # Columns
    571eaa99-3b98-41a7-8942-c300b3c2fe5b: Byline # Byline
    721f6c59-d353-4810-9d84-eee327f296be: 'Minus Margin Bottom' # Minus Margin Bottom
    798cf224-57ed-4c61-bc6d-17cd588d0799: Home # Home
    811baf06-6695-4229-9067-1b2f8a49e13c: Images # Images
    970e66f8-69d9-430c-b4f9-74359ab8d3bd: Advanced # Advanced
    982eeecd-95ad-43d1-8cc2-f6b3d80be494: 'Basic Content' # Basic Content
    5249fb26-5dbb-40d0-8d43-eaa65ad75be1: Header # Header
    6065b222-611d-42ce-a1de-85a02891694c: 'Background Color' # Background Color
    8078a4c8-2881-4519-9e4a-e50fbd74a5eb: 'Featured Banner' # Featured Banner
    8893b951-cdef-4627-b3d4-e6a892beec77: Pages # Pages
    9898b51a-08e7-4470-9553-ccca82c2fd7b: Solid # Solid
    13612fd6-fab3-4e45-9853-5634a3ef9d91: CTA # CTA
    29046eec-f132-4f06-8bc6-2289a453e2b9: Split # Split
    31901f15-b181-4b05-8ae6-b070031679db: 'Icon Position' # Icon Position
    72886fe1-8cd7-4787-bc4b-1b0a49aa82ba: 'Image Content' # Image Content
    395545e5-c12d-445f-b791-fe195138302c: 'General Information' # General Information
    434146a4-9bb6-41fc-8ce9-984ed4921d55: Country # Country
    948968bb-c8d8-4627-aaa9-aa1b20ada200: Hero # Hero
    21102308-0ca8-4b67-8663-daef265f4c60: 'Animation?' # Animation?
    97532141-63d3-4bec-a94a-313c6e99fefa: 'Button Color' # Button Color
    a09ca3ab-fe0a-4cb3-83bd-6f37f4fd3260: 'Public Schema' # Public Schema
    a579166c-0d8c-47c9-ba09-8eaa6ca4cdd9: 'Image Position 2' # Image Position 2
    aeac151d-d4a9-4733-9c2f-c8a1eac9a41b: 'Content Width' # Content Width
    af56b8d4-e8df-4952-96c3-24e39909380c: 'IJM Program Tracker' # IJM Program Tracker
    bac5974c-f86b-4ef2-a13c-d4e61c2883b7: Jurisdictions # Jurisdictions
    bc3b468e-cdba-4c0b-b35e-eec6078f0472: Root # Root
    bc97ce21-40cf-43a2-991d-94585d8fb43a: 'Icon Card' # Icon Card
    bcbc592a-d4d0-4afa-92b6-458504f09b17: 'Margin Top' # Margin Top
    c54b7104-c058-41f4-ac16-278920cf8062: 'Container Size' # Container Size
    c14150f6-d51e-480d-9575-1091c8b07cb1: 'Content Builder' # Content Builder
    cf6c9928-e050-4212-a498-0618e38611b1: Country # Country
    cfc164dd-7161-4a3d-9407-1080228e7455: 'Content Alignment' # Content Alignment
    d07b837d-c20e-48d9-ac52-34b7a29fbfcb: 'Container Id' # Container Id
    d3ab5ad8-585b-43bc-b8ad-c093a04c787f: 'Minus Margin Top' # Minus Margin Top
    d381de9e-9630-4674-827e-b9e59ed8b921: 'Contact Form' # Contact Form
    dcc4c3a7-d1ad-429a-8db7-6eb780b2d453: 'Dots in group of' # Dots in group of
    dccbbef1-4f06-4d4c-ae48-1cf7043ddc36: 'Alt Logo' # Alt Logo
    e0a8ee1c-ea61-4169-aea6-03da5e26c04f: Column # Column
    e0e47b5e-62b4-4b02-aeca-99868e8625d9: 'Animation Duration' # Animation Duration
    e05fb8e0-726b-4a55-b97f-aea98a58c8a1: 'Heading Size' # Heading Size
    e671a976-5fd4-4e36-a257-592286dfcf78: 'Image Position' # Image Position
    e9322ff0-91a2-4b27-9c44-ac0b405460c2: 'Nav Links' # Nav Links
    e434669f-dd5f-4232-88ef-7a3b8c37b4dc: Column # Column
    ea3ff1c6-5aea-4ffe-8849-124fd7287995: New # New
    ec8cf3c5-a3d4-4c87-9c99-6807bee72059: 'Two Columns' # Two Columns
    ef7dff82-7ddc-453d-b03e-6b90683f02bd: 'Font Weight' # Font Weight
    efbbee8b-1252-4404-9606-10025e02711b: 'Column Layout' # Column Layout
    f0cc5f70-7696-4267-8c7c-769e499ad9de: Videos # Videos
    f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7: Buttons # Buttons
    f8f1ebd9-1ace-4716-a3fc-03f5bcf95cbd: Stages # Stages
    f36b49ea-9938-42fb-9803-9772a378f173: 'Overlay Opacity' # Overlay Opacity
    fa195a9b-e2f8-4ff9-b875-48e5cce85e25: 'Image Content Layout' # Image Content Layout
    fd3064ce-7808-4f58-bc09-64a40469022d: Casework # Casework
plugins:
  _ijm-project-tracker-custom-plugin:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  buttonbox:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cloudflare:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  craft-range-slider:
    edition: standard
    enabled: true
    licenseKey: XTK8R84UVOIS7OAIWIRR2JG3
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: WIQUZC8QRUXW7HIY5D0Z4905
    schemaVersion: 3.4.6
  hyper:
    edition: standard
    enabled: true
    licenseKey: H96AXCHZR4LITRZ62BM6TX0X
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: K92IKU3RM8LPX6SIY0BGAD2Y
    schemaVersion: 1.2.3
    settings:
      enableCache: true
      iconItemSize: 32
      iconItemSizeLarge: 40
      iconItemWrapperSize: 56
      iconItemWrapperSizeLarge: 72
      iconSetsPath: '@webroot/icons/'
      iconSetsUrl: '@web/icons/'
      redactorFieldHandle: ''
  imager-x:
    edition: pro
    enabled: true
    licenseKey: V5RA73U38PF7P7A7MKHI0A89
    schemaVersion: 4.0.0
  imager-x-do-spaces-driver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  keychain:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrix-extended:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 4A9NGKFKTS61WKHQ0RLFS5NF
    schemaVersion: 2.1.0
  neo:
    edition: standard
    enabled: true
    licenseKey: 8NBR5V21CE3HK6A4K8927WNJ
    schemaVersion: 5.0.0.1
  nocache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  saml-sp:
    edition: standard
    enabled: true
    licenseKey: YTKZ506RHWUCO2P2AHUNP4O7
    schemaVersion: 2.1.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: MM9T4KW8F4JJN4FVAEDW37MZ
    schemaVersion: 3.0.12
  simplemap:
    edition: lite
    enabled: true
    schemaVersion: 3.4.2
  super-dynamic-fields:
    edition: standard
    enabled: true
    licenseKey: MZE883HWLAI6YMOU1JFLIX72
    schemaVersion: 5.0.1
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'IJM Program Tracker'
  retryDuration: null
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
