dateModified: 1724157563
email:
  fromEmail: mufi@paragonn.com
  fromName: 'IJM Program Tracker'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -t -i'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/uploads/transforms'
    type: craft\fs\Local
    url: '@web/uploads/transforms'
  videos:
    hasUrls: true
    name: Videos
    settings:
      path: '@webroot/uploads/videos'
    type: craft\fs\Local
    url: '@web/uploads/videos'
meta:
  __names__:
    0b15cab4-22ae-40f3-9612-204b951f30f0: Image # Image
    0bb1f59a-bac9-4368-b972-bc346cf78bdb: Links # Links
    0d8c4992-13e5-49e7-bc75-c6a7036cd8fc: 'Tracking Scripts' # Tracking Scripts
    0e13a17a-1829-4ccb-a64f-c39b6d62af82: 'Animation Offset' # Animation Offset
    0e63aa9f-6064-4094-ab28-0b9e7f6b8f09: 'Image + Content' # Image + Content
    00f64a37-6342-4ab0-a52b-d24123cb37e0: 'Info Box' # Info Box
    1cbb1390-2bb5-47d8-afaa-fb0146a8e4d0: 'Code / Embed' # Code / Embed
    1cf2528d-1b25-4d76-be36-e58ac8a4d68b: 'Stats Box' # Stats Box
    1da620f4-95cb-4911-9332-8ef04cad860f: Button # Button
    01f461ba-4bc8-44aa-9f3a-797489f1fcc5: Editor # Editor
    02c1f367-dcb0-49f9-af0b-e255d2928b19: 'Show Border?' # Show Border?
    2e9cec4b-7c08-4594-a616-22bb4a04cba8: Brands # Brands
    3b2d250a-efd7-4394-9e59-a1ae3b9d5292: 'Animation Style' # Animation Style
    3bf73e53-2279-498c-9693-f24c6e498172: 'Page Builder' # Page Builder
    3c44034a-42a6-4e12-a863-4f3cc325f1a4: 'Padding Top' # Padding Top
    3d2181fb-3192-45b5-8817-c25be592f8e2: Accordion # Accordion
    3d6985d0-6c25-467d-8334-100bb6a30cce: 'Call to Action' # Call to Action
    3fc2d296-ed56-4d93-a0e3-435f9f12a54c: CTA # CTA
    4b89198b-d038-4943-ae58-1f0c6d1ccc8d: Stage # Stage
    4d0f80d5-2179-4e31-89b1-569192b6e7fd: 'Check List Layout' # Check List Layout
    4f72c1ee-9438-4229-aa23-ef809d4af047: Logo # Logo
    5a2e4125-53c6-4343-b44e-970c058d6ba3: 'Projects Search Feature with MapBox' # Projects Search Feature with MapBox
    5c6bb440-978c-4cab-8939-e7991f378b17: Custom # Custom
    5c654d1e-8c51-46d6-9baa-d89900c8051a: 'Icon Card' # Icon Card
    5d2385da-c451-4d15-a8dc-9bf204cfb717: Eyebrow # Eyebrow
    5e460cf8-38e4-4ac9-8629-0c53ed9052c4: Jurisdictions # Jurisdictions
    05ed830d-e0d9-45c1-a952-f81bb441a524: 'Script Position' # Script Position
    05f4aa96-2a20-4f5a-af29-371b169a6725: 'Current Status' # Current Status
    6a8efaa8-2ed0-497f-a528-78203c0632ab: 'Hero Image' # Hero Image
    6ae7d75d-cf9a-41db-b14d-a11c5a609f43: Icon # Icon
    7afc8aef-c2ce-4275-ab1d-9a25238e9304: 'Javascript Code' # Javascript Code
    7b26f9bb-9eda-45e3-878a-0530263e4d2b: 'Stacked Cards' # Stacked Cards
    7bc32678-0f69-4111-926c-26e502c0c7fc: '1 Blank at?' # 1 Blank at?
    7be90189-1791-495b-a850-3bc340df0caf: Casework # Casework
    7d09c5e7-e849-465a-9e4f-087bdef82bb4: Caption # Caption
    7f018fb5-73a1-482a-97e6-20b925125348: Videos # Videos
    7fe9589b-0f2b-4c94-91b8-f1e030710e58: Regular # Regular
    8df78e11-4ebe-4815-a6a8-a9a62e77b6d6: 'Animation Easing' # Animation Easing
    8ee03cb6-c673-4aca-b24c-41391b451ecf: 'Number of Dots' # Number of Dots
    08f0c8e2-e9c0-426a-aab3-861fbf413a1f: Heading # Heading
    8fe9110f-04ca-4e39-bd2e-0bce67301c39: Simple # Simple
    9affc432-fe49-4e90-96ea-be5425095c2c: 'Margin Bottom' # Margin Bottom
    9b1a133a-4d4f-4a24-bb40-e59834fea921: Container # Container
    9ce08183-1391-4b24-8288-a39ac4f97186: 'Image Ratio' # Image Ratio
    9ea500de-6e50-41cc-a7ad-a1a5aeb0aca6: 'Image Content Slide' # Image Content Slide
    9eeafc05-3901-41da-8748-e04485b292cb: 'Button Type' # Button Type
    14cf885b-68f2-4ea2-8f07-4a707cc2677f: 'Info Box Layout' # Info Box Layout
    16c21eca-a8b2-4b44-bd82-463fac26b779: 'Icon Cards' # Icon Cards
    18de2689-3603-4c37-8473-396f9ce4f78c: 'Padding Bottom' # Padding Bottom
    021cf0d0-1863-4788-aeb4-6225da5b03a9: 'Embed Video' # Embed Video
    24e627ff-4926-4819-9fc1-9efb83576180: 'Margin Style' # Margin Style
    26c9ce02-0df9-486a-90b7-104efcd7f5a8: 'Content Box Color' # Content Box Color
    28ccf5ae-cf72-492b-94c0-edbbbd1f411e: Checklist # Checklist
    28f860da-7e14-4288-a55f-bce3b2856d85: Text # Text
    39a76ad9-6746-4fb7-be42-bd92bcd72610: Answers # Answers
    45decbb3-802d-4a8a-9b63-3067d0c45d17: 'Require Login?' # Require Login?
    51e378c8-6e12-44cb-ae38-9b5c9703adfd: 'Per Row Limit' # Per Row Limit
    59f089df-32db-4da9-aa07-7b501b160aa4: Card # Card
    60cbc150-308a-4195-882f-fe574c5af2d0: Image # Image
    061c5a97-e8a9-4593-9f93-8a54597d62b4: 'IJM Program Tracker' # IJM Program Tracker
    68a24557-cc86-4045-b642-754749ccf485: 'Stage Byline' # Stage Byline
    71fa55a9-c465-4fe2-91f2-ee5a739774a9: 'Overlay Gradient' # Overlay Gradient
    75f7ed78-7f7c-432f-a6f5-b028a8b82c52: Stages # Stages
    89cc861f-51a9-49de-9637-831af3da0e7a: 'Border Color' # Border Color
    089d8bf1-7cfe-4f80-bf8b-517fa9e233e0: 'Call to Action' # Call to Action
    90a810f2-de87-4697-8abf-8e6e2c825c72: Quote # Quote
    95b9f0e3-06b5-4fdf-add4-4d87ad204c7e: Address # Address
    383b8156-a3da-4bda-991a-7c9893a1c11c: Button # Button
    423bb166-71e5-4c7c-9d8c-71db99966b0b: SEO # SEO
    451e39c8-4f34-47b0-9a76-9fae1d662c17: Columns # Columns
    493bf7e3-b061-45e5-92e4-2f401b9a8e5a: 'Status Card' # Status Card
    571eaa99-3b98-41a7-8942-c300b3c2fe5b: Byline # Byline
    677ee826-6c97-4489-8594-51d62514994d: Accordions # Accordions
    703c4614-7d62-46a6-927a-23935a1f6c22: 'Status Cards' # Status Cards
    798cf224-57ed-4c61-bc6d-17cd588d0799: Home # Home
    811baf06-6695-4229-9067-1b2f8a49e13c: Images # Images
    887e8c04-ed78-4f44-afb0-408021c88446: 'Background Image' # Background Image
    910dab4f-1758-4717-b8f9-e8b63a73f3de: 'HTML Code' # HTML Code
    970e66f8-69d9-430c-b4f9-74359ab8d3bd: Advanced # Advanced
    982eeecd-95ad-43d1-8cc2-f6b3d80be494: 'Basic Content' # Basic Content
    5249fb26-5dbb-40d0-8d43-eaa65ad75be1: Header # Header
    5581efe6-f333-49f1-8b13-ac5d43570282: 'View Only' # View Only
    6065b222-611d-42ce-a1de-85a02891694c: 'Background Color' # Background Color
    6352b785-b04c-4d99-befd-2f5f5308c36b: 'Stacked Card' # Stacked Card
    6553bc6c-dfc2-465a-a5ba-e218ea8c0778: 'Jurisdictions Case Types' # Jurisdictions Case Types
    8078a4c8-2881-4519-9e4a-e50fbd74a5eb: 'Featured Banner' # Featured Banner
    8257b009-c3c8-4465-beb9-fa52c9b6be4f: 'Status Color ' # Status Color 
    8893b951-cdef-4627-b3d4-e6a892beec77: Pages # Pages
    9898b51a-08e7-4470-9553-ccca82c2fd7b: Solid # Solid
    10939aae-e10b-4be1-8d12-358d50ce590d: 'Stat Box' # Stat Box
    13612fd6-fab3-4e45-9853-5634a3ef9d91: CTA # CTA
    23661aee-cd9b-46df-9aa0-3f931f87ba19: card # card
    29046eec-f132-4f06-8bc6-2289a453e2b9: Split # Split
    31901f15-b181-4b05-8ae6-b070031679db: 'Icon Position' # Icon Position
    56196e9b-e1c4-44b3-817a-0f471121ed32: 'Quote Attribution' # Quote Attribution
    67356d1e-de3d-4ceb-85ad-abf6b08ff9d2: 'Tracking Script' # Tracking Script
    72886fe1-8cd7-4787-bc4b-1b0a49aa82ba: 'Image Content' # Image Content
    395545e5-c12d-445f-b791-fe195138302c: 'General Information' # General Information
    434146a4-9bb6-41fc-8ce9-984ed4921d55: Country # Country
    948968bb-c8d8-4627-aaa9-aa1b20ada200: Hero # Hero
    21102308-0ca8-4b67-8663-daef265f4c60: 'Animation?' # Animation?
    45855582-b74b-4405-9639-34fc6b00d637: 'Add only in Production?' # Add only in Production?
    97532141-63d3-4bec-a94a-313c6e99fefa: 'Button Color' # Button Color
    a08b46e9-7b38-45d1-98d4-7b4a827012ac: Accordion # Accordion
    a09ca3ab-fe0a-4cb3-83bd-6f37f4fd3260: 'Public Schema' # Public Schema
    a32f779d-1477-4234-a85c-8cf2b02d2d83: 'Stacked Card' # Stacked Card
    a134d66d-e5d8-439a-bc68-e947c91e759b: Container # Container
    a579166c-0d8c-47c9-ba09-8eaa6ca4cdd9: 'Image Position 2' # Image Position 2
    ab7328c2-0ac9-4a96-8ed5-054ee9e45cbf: 'Per Row Limit' # Per Row Limit
    aeac151d-d4a9-4733-9c2f-c8a1eac9a41b: 'Content Width' # Content Width
    af56b8d4-e8df-4952-96c3-24e39909380c: 'IJM Program Tracker' # IJM Program Tracker
    bac5974c-f86b-4ef2-a13c-d4e61c2883b7: Jurisdictions # Jurisdictions
    bc97ce21-40cf-43a2-991d-94585d8fb43a: 'Icon Card' # Icon Card
    bcbc592a-d4d0-4afa-92b6-458504f09b17: 'Margin Top' # Margin Top
    be56efe1-2490-448d-9cf5-ac5c92a43952: 'Tracking Scripts' # Tracking Scripts
    c0909bba-5350-4f48-875b-48151f1f9f7c: 'Script Files' # Script Files
    c54b7104-c058-41f4-ac16-278920cf8062: 'Container Size' # Container Size
    c14150f6-d51e-480d-9575-1091c8b07cb1: 'Content Builder' # Content Builder
    cf6c9928-e050-4212-a498-0618e38611b1: Country # Country
    cfc164dd-7161-4a3d-9407-1080228e7455: 'Content Alignment' # Content Alignment
    d07b837d-c20e-48d9-ac52-34b7a29fbfcb: 'Container Id' # Container Id
    d1abafe9-7def-492a-8370-693e6103efe8: 'Check List Table' # Check List Table
    d381de9e-9630-4674-827e-b9e59ed8b921: 'Contact Form' # Contact Form
    d5783338-8a9d-4621-8556-71a156306314: Cards # Cards
    dcc4c3a7-d1ad-429a-8db7-6eb780b2d453: 'Dots in group of' # Dots in group of
    dccbbef1-4f06-4d4c-ae48-1cf7043ddc36: 'Alt Logo' # Alt Logo
    e0a8ee1c-ea61-4169-aea6-03da5e26c04f: Column # Column
    e0e47b5e-62b4-4b02-aeca-99868e8625d9: 'Animation Duration' # Animation Duration
    e05fb8e0-726b-4a55-b97f-aea98a58c8a1: 'Heading Size' # Heading Size
    e671a976-5fd4-4e36-a257-592286dfcf78: 'Image Position' # Image Position
    e9322ff0-91a2-4b27-9c44-ac0b405460c2: 'Nav Links' # Nav Links
    e434669f-dd5f-4232-88ef-7a3b8c37b4dc: Column # Column
    ea3ff1c6-5aea-4ffe-8849-124fd7287995: New # New
    ec8cf3c5-a3d4-4c87-9c99-6807bee72059: 'Two Columns' # Two Columns
    ef7dff82-7ddc-453d-b03e-6b90683f02bd: 'Font Weight' # Font Weight
    efbbee8b-1252-4404-9606-10025e02711b: 'Column Layout' # Column Layout
    f0cc5f70-7696-4267-8c7c-769e499ad9de: Videos # Videos
    f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7: Buttons # Buttons
    f8f1ebd9-1ace-4716-a3fc-03f5bcf95cbd: Stages # Stages
    f9be8226-8b11-4ea4-8950-2dbcb61beec5: 'Column Alignment' # Column Alignment
    f9eba964-5011-423c-a0cc-36c5554f82ce: 'Status Card' # Status Card
    f36b49ea-9938-42fb-9803-9772a378f173: 'Overlay Opacity' # Overlay Opacity
    f53d3737-57cc-49ff-b173-17376ae0c1bf: 'Stat Box' # Stat Box
    fa195a9b-e2f8-4ff9-b875-48e5cce85e25: 'Image Content Layout' # Image Content Layout
    fd3064ce-7808-4f58-bc09-64a40469022d: Casework # Casework
plugins:
  _ijm-project-tracker-custom-plugin:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  buttonbox:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cloudflare:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  craft-range-slider:
    edition: standard
    enabled: true
    licenseKey: XTK8R84UVOIS7OAIWIRR2JG3
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: WIQUZC8QRUXW7HIY5D0Z4905
    schemaVersion: 3.4.6
  hyper:
    edition: standard
    enabled: true
    licenseKey: H96AXCHZR4LITRZ62BM6TX0X
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: K92IKU3RM8LPX6SIY0BGAD2Y
    schemaVersion: 1.2.3
    settings:
      enableCache: true
      iconItemSize: 32
      iconItemSizeLarge: 40
      iconItemWrapperSize: 56
      iconItemWrapperSizeLarge: 72
      iconSetsPath: '@webroot/icons/'
      iconSetsUrl: '@web/icons/'
      redactorFieldHandle: ''
  imager-x:
    edition: pro
    enabled: true
    licenseKey: V5RA73U38PF7P7A7MKHI0A89
    schemaVersion: 4.0.0
  imager-x-do-spaces-driver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  keychain:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrix-extended:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 4A9NGKFKTS61WKHQ0RLFS5NF
    schemaVersion: 2.1.0
  neo:
    edition: standard
    enabled: true
    licenseKey: 8NBR5V21CE3HK6A4K8927WNJ
    schemaVersion: 5.0.0.1
  nocache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  saml-sp:
    edition: standard
    enabled: true
    licenseKey: YTKZ506RHWUCO2P2AHUNP4O7
    schemaVersion: 2.1.0
    settings:
      autoCreateGroups: true
      createUser: true
      enableCpLoginButtons: true
      enableUsers: true
      encodeRelayState: true
      endpointPrefix: sso
      entityId: $SSO_ENTITY_ID
      groupAttributeNames:
        - groups
      mergeExistingGroups: true
      mergeLocalUsers: true
      nameIdAttributeOverride: null
      relayStateOverrideParam: RelayState
      requireAssertionToBeSigned: true
      requireResponseToBeSigned: false
      responseAttributeMap:
        __assoc__:
          -
            - 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'
            - email
          -
            - 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname'
            - firstName
          -
            - 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'
            - lastName
          -
            - email
            - email
          -
            - firstName
            - firstName
          -
            - lastName
            - lastName
      signAuthnRequest: true
      sloDestroySpecifiedSessions: false
      syncGroups: true
      wantsSignedAssertions: true
  seomatic:
    edition: standard
    enabled: true
    licenseKey: MM9T4KW8F4JJN4FVAEDW37MZ
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: ''
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableDebugToolbarPanel: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
      xDefaultSite: 0
  simplemap:
    edition: lite
    enabled: true
    schemaVersion: 3.4.2
  super-dynamic-fields:
    edition: standard
    enabled: true
    licenseKey: MZE883HWLAI6YMOU1JFLIX72
    schemaVersion: 5.0.1
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'IJM Program Tracker'
  retryDuration: null
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
