defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3bf73e53-2279-498c-9693-f24c6e498172 # Page Builder
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  af56b8d4-e8df-4952-96c3-24e39909380c: # IJM Progress Tracker
    enabledByDefault: true
    hasUrls: true
    template: _home/index.twig
    uriFormat: __home__
type: single
