defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3bf73e53-2279-498c-9693-f24c6e498172
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af56b8d4-e8df-4952-96c3-24e39909380c:
    enabledByDefault: true
    hasUrls: true
    template: _pages/index.twig
    uriFormat: '{parent.uri}/{slug}'
type: channel
